language: node_js
arch:
  - amd64
  - ppc64le
sudo: false
node_js:
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"

script:
  - npm test
  - if [[ ${TRAVIS_NODE_VERSION} == "8" ]]; then npm run coverage; fi;
